### ISSUE TITLE
Explicar el habilitar cámara

### ISSUE THREAD

**Issue by code-sur** [quiensosahora/quiensosahora.github.io#1]
Me resulta molesto en general los sitios que te piden permisos de dispositivos sin explicar para qué.
Creo que podría sumar a la experiencia, comentar brevemente que se necesita de la cámara y luego que te pida de habilitar.

Ejemplo
![Screen Shot 2024-07-13 at 18 52 17](https://github.com/user-attachments/assets/65ef45b9-19b5-4323-9c7b-243995df000e)

**Comment by naysolange** [comment]
Esto sí a full. Lo vengo pensando hace rato porque me pasa lo mismo pero aún no lo había hecho. Me gusta tu propuesta de aclarar que no se persiste imagen porque para mí es algo obvio pero no para todo el mundo.
