### ISSUE TITLE
Para qué sirve el botón changeCamera?

### ISSUE THREAD

**Issue by code-sur** [quiensosahora/quiensosahora.github.io#4]
¿Para qué sirve este botón?
Asumo que es para cambiar de cámara (frontal o trasera) en mobile pero, yo estoy probando en PC y ese botón no hace nada.

![Screen Shot 2024-07-13 at 19 09 38](https://github.com/user-attachments/assets/d36c8b94-7272-49ce-a867-6939f9373cf0)

**Comment by naysolange** [comment]
Tal cual. Tengo una idea para eso que aún no implementé.
